---
version: '3.10'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgsql
    ports:
      - 5432:5432
    healthcheck:
      # https://github.com/peter-evans/docker-compose-healthcheck/issues/16
      test: ["CMD", "pg_isready", "q", "-U", "postgres", "-d", "pgsql"]
      interval: 10s
      timeout: 5s
      retries: 5
